### ISSUE TITLE
Plugin not working (says "null")

### ISSUE THREAD

**Issue by steve1977** [realies/corsairpsu-unraid#1]
I have a Corsair RM1000i. I was excited to see this plugin for Unraid and installed it. After successful install, it doesn't show anything. See copy&paste below:

Uptime | Temp1 / Temp2 | Fan RPM | Supply Volts | Nominal Power | GPU Load | PSU Load | PSU Load %
-- | -- | -- | -- | -- | -- | -- | --
null

**Comment by realies** [comment]
We resolved this after all, although please use https://github.com/CyanLabs/corsairpsu-unraid
